version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: investment_web
    # '/start' is the shell script used to run the service
    command: run-server
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DJANGO_ENV=develop
      - SECRET_KEY="django-insecure-saaon@mps#b+h8=00ee_)%1h1ua5fp%rnj5pvu)80z*@=90xe"
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - redis
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis
    ports:
      - 6379:6379

  celery_worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: investment_celery_worker
    command: run-worker
    volumes:
      - .:/app
    environment:
      - DJANGO_ENV=develop
      - SECRET_KEY="django-insecure-saaon@mps#b+h8=00ee_)%1h1ua5fp%rnj5pvu)80z*@=90xe"
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: investment_celery_beat
    command: run-beat
    volumes:
      - .:/app
    environment:
      - DJANGO_ENV=develop
      - SECRET_KEY="django-insecure-saaon@mps#b+h8=00ee_)%1h1ua5fp%rnj5pvu)80z*@=90xe"
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - redis
      - db

#  flower:
#    build:
#      context: .
#      dockerfile: ./docker/Dockerfile
#    image: investment_celery_flower
#    command: run-flower
#    volumes:
#      - .:/app
#    env_file:
#      - .env
#    ports:
#      - 5557:5555
#    depends_on:
#      - redis
#      - db

volumes:
  postgres_data: